package SequencesDB::Model::DB;

use strict;
use warnings;
use base 'Catalyst::Model::DBIC::Schema';
use Config::Tiny;
use File::Basename;
use Carp;

# Load database configuration from external file
my $config_file = dirname(__FILE__) . '/../../../../config/database.conf';
my $config = Config::Tiny->read($config_file);

unless ($config && $config->{database}) {
    # Fallback to environment variables if config file is not available
    $config = {
        database => {
            dsn      => $ENV{SEQUENCES_DB_DSN} || 'dbi:mysql:sequences_dtb',
            user     => $ENV{SEQUENCES_DB_USER} || 'sequences_user',
            password => $ENV{SEQUENCES_DB_PASSWORD} || '',
            host     => $ENV{SEQUENCES_DB_HOST} || 'localhost',
            port     => $ENV{SEQUENCES_DB_PORT} || 3306,
        }
    };
}

__PACKAGE__->config(
    schema_class => 'SequencesDB::Schema',
    
    connect_info => {
        dsn      => $config->{database}{dsn},
        user     => $config->{database}{user},
        password => $config->{database}{password},
        
        # Connection options for better performance and security
        mysql_enable_utf8 => 1,
        mysql_auto_reconnect => 1,
        on_connect_do => [
            "SET NAMES utf8",
            "SET sql_mode='STRICT_TRANS_TABLES'",
        ],
        
        # Connection pool settings
        mysql_use_result => 1,
        mysql_multi_statements => 1,
        
        # Error handling
        RaiseError => 1,
        PrintError => 0,
        AutoCommit => 1,
        
        # Quote identifiers to prevent SQL injection
        quote_names => 1,
    }
);

=head1 NAME

SequencesDB::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SequencesDB>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SequencesDB::Schema>

This model now uses externalized configuration for database credentials
and includes enhanced security and performance settings.

=head1 CONFIGURATION

The model looks for database configuration in the following order:
1. config/database.conf file
2. Environment variables:
   - SEQUENCES_DB_DSN
   - SEQUENCES_DB_USER
   - SEQUENCES_DB_PASSWORD
   - SEQUENCES_DB_HOST
   - SEQUENCES_DB_PORT

=head1 SECURITY FEATURES

- Externalized database credentials
- SQL injection protection with quoted identifiers
- Strict transaction mode
- UTF-8 support with proper encoding
- Connection pooling for better performance

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65 (Refactored)

=head1 AUTHOR

Edoardo (Refactored for security and maintainability)

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;